name: recodai-sifd
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy=2.4.4
  - pillow=12.2.0
  - opencv
  - matplotlib=3.10.9
  - pandas=3.0.2
  - scikit-image=0.26.0
  - scikit-learn=1.8.0
  - tqdm=4.67.3
  - scipy=1.17.1
  - numba=0.65.1
  - pyyaml=6.0.3
  - jupyterlab
  - ipykernel
  - pip:
      - opencv-contrib-python==4.13.0.92
      - onnxruntime==1.25.1
      - loguru==0.7.3
      - numba==0.65.1
      - torch==2.11.0
      - torchvision==0.26.0
      - timm==1.0.26
      - huggingface_hub==1.13.0
      - safetensors==0.7.0
      - rich==15.0.0
      - typer==0.25.1
      - pytest